version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/tododb
      - JWT_SECRET=secret-123
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND=http://backend:8080
    depends_on:
      - backend

volumes:
  mongo-data:
